# Generated by Django 2.0.7 on 2018-07-25 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.PositiveIntegerField(choices=[(101, 'FUNCIONARIO'), (102, 'GESTOR')], verbose_name='Tipo de usuário')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de usuário',
                'verbose_name_plural': 'perfis de usuários',
                'permissions': (('can_see_all_files', 'Ver todos os arquivos'), ('can_manage_user_information', 'Gerenciar informações de usuários'), ('can_read_usage_information', 'Ver informações de utilização'), ('can_manage_upload_limit', 'Gerenciar limite de upload'), ('can_change_own_name', 'Alterar o próprio nome'), ('can_change_own_email', 'Alterar o próprio email')),
            },
        ),
    ]
