# Generated by Django 2.0.7 on 2018-07-26 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False, verbose_name='público')),
                ('upload', models.FileField(upload_to=user_profile.models.user_directory_path)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.PositiveIntegerField(choices=[(101, 'FUNCIONARIO'), (102, 'GESTOR')], verbose_name='Tipo de usuário')),
                ('full_address', models.CharField(max_length=255, verbose_name='Endereço completo')),
                ('city_state', models.CharField(max_length=50, verbose_name='Cidade - UF')),
                ('upload_volume_limit', models.PositiveIntegerField(blank=True, help_text='Volume de dados máximo de arquivos do usuário', null=True, verbose_name='limite de volume de arquivos')),
                ('upload_number_limit', models.PositiveIntegerField(blank=True, help_text='Número máximo de arquivos do usuário', null=True, verbose_name='limite de máximo de arquivos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de usuário',
                'verbose_name_plural': 'perfis de usuários',
                'permissions': (('can_see_all_files', 'Ver todos os arquivos'), ('can_manage_user_information', 'Gerenciar informações de usuários'), ('can_read_usage_information', 'Ver informações de utilização'), ('can_manage_upload_limit', 'Gerenciar limite de upload'), ('can_change_own_name', 'Alterar o próprio nome'), ('can_change_own_email', 'Alterar o próprio email')),
            },
        ),
    ]
