# Generated by Django 2.0.7 on 2018-07-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180725_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city_state',
            field=models.CharField(default='', max_length=50, verbose_name='Cidade - UF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_address',
            field=models.CharField(default='', max_length=255, verbose_name='Endereço completo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='upload_number_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Número máximo de arquivos do usuário', null=True, verbose_name='limite de máximo de arquivos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='upload_volume_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Volume de dados máximo de arquivos do usuário', null=True, verbose_name='limite de volume de arquivos'),
        ),
    ]
